version: "3.8"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=root-token
    volumes:
      - vault-dev-data:/vault

  vault-prod:
    image: custom-vault:latest
    ports:
      - "8201:8200"
    volumes:
      - vault-prod-data:/vault/data
      - ./vault-config.hcl:/vault/config/vault-config.hcl
      - ./vault-entrypoint.sh:/vault-entrypoint.sh
      - ./unseal-keys.txt:/vault/keys/unseal-keys.txt
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    entrypoint: ["/bin/sh", "/vault-entrypoint.sh"]

volumes:
  vault-dev-data:
  vault-prod-data:
